import { RuleDefinition, RuleSelectionState } from '../types';

export const ALL_RULES: RuleDefinition[] = [
  // Boundary Limits
  {
    id: 'numericMinMinusOne',
    name: 'Numeric Minimum - 1 (Underflow)',
    category: 'boundary',
    description: 'Mutates numeric values to 1 below minimum or exclusiveMinimum constraint',
    defaultEnabled: true,
    severity: 'high',
  },
  {
    id: 'numericMaxPlusOne',
    name: 'Numeric Maximum + 1 (Overflow)',
    category: 'boundary',
    description: 'Mutates numeric values to 1 above maximum or exclusiveMaximum constraint',
    defaultEnabled: true,
    severity: 'high',
  },
  {
    id: 'numericZeroAndNegative',
    name: 'Zero & Negative Values',
    category: 'boundary',
    description: 'Injects 0 and -1 into unsigned/positive-only numeric fields',
    defaultEnabled: true,
    severity: 'medium',
  },
  {
    id: 'numericOverflow',
    name: 'Safe Integer Overflow (MAX_SAFE_INTEGER + 1)',
    category: 'boundary',
    description: 'Tests integer precision limits by exceeding JS 64-bit float precision',
    defaultEnabled: true,
    severity: 'medium',
  },
  {
    id: 'stringMinLengthMinusOne',
    name: 'String minLength - 1',
    category: 'boundary',
    description: 'Truncates string to 1 char shorter than minLength constraint',
    defaultEnabled: true,
    severity: 'high',
  },
  {
    id: 'stringMaxLengthPlusOne',
    name: 'String maxLength + 1',
    category: 'boundary',
    description: 'Expands string to 1 char longer than maxLength constraint',
    defaultEnabled: true,
    severity: 'high',
  },
  {
    id: 'stringBufferOverflow',
    name: 'String Buffer Flood (10,000+ chars)',
    category: 'boundary',
    description: 'Floods string fields with a 10KB string to test payload limits & DoS resilience',
    defaultEnabled: false,
    severity: 'medium',
  },
  {
    id: 'stringEmpty',
    name: 'Empty String ("")',
    category: 'boundary',
    description: 'Injects an empty string into required string fields',
    defaultEnabled: true,
    severity: 'medium',
  },
  {
    id: 'arrayEmpty',
    name: 'Empty Array ([])',
    category: 'boundary',
    description: 'Injects empty arrays into fields with minItems >= 1',
    defaultEnabled: true,
    severity: 'high',
  },
  {
    id: 'arrayMaxItemsPlusOne',
    name: 'Array maxItems + 1',
    category: 'boundary',
    description: 'Appends an extra item exceeding maxItems limit',
    defaultEnabled: true,
    severity: 'medium',
  },

  // Null & Omission
  {
    id: 'omitRequiredFields',
    name: 'Omit Required Field',
    category: 'nullability',
    description: 'Deletes each required property from the request body',
    defaultEnabled: true,
    severity: 'high',
  },
  {
    id: 'explicitNullForNonNull',
    name: 'Explicit null for Non-Nullable Fields',
    category: 'nullability',
    description: 'Sets non-nullable properties explicitly to null',
    defaultEnabled: true,
    severity: 'high',
  },
  {
    id: 'emptyObjectsForRequired',
    name: 'Empty Object ({}) for Nested Objects',
    category: 'nullability',
    description: 'Replaces populated complex objects with empty objects {}',
    defaultEnabled: true,
    severity: 'medium',
  },
  {
    id: 'arrayNullItemInjection',
    name: 'Null Item Injection in Arrays',
    category: 'nullability',
    description: 'Injects [null] or null elements into typed lists',
    defaultEnabled: false,
    severity: 'medium',
  },

  // Type Mismatches
  {
    id: 'stringToInteger',
    name: 'String → Integer Mismatch',
    category: 'type_mismatch',
    description: 'Replaces string fields with numeric integers (e.g. 123456)',
    defaultEnabled: true,
    severity: 'high',
  },
  {
    id: 'integerToString',
    name: 'Integer → String Mismatch',
    category: 'type_mismatch',
    description: 'Replaces integer fields with alphanumeric strings (e.g. "invalid_number")',
    defaultEnabled: true,
    severity: 'high',
  },
  {
    id: 'booleanToString',
    name: 'Boolean → String ("true" / "false")',
    category: 'type_mismatch',
    description: 'Tests boolean type coercion by sending string literals "true" or "false"',
    defaultEnabled: true,
    severity: 'medium',
  },
  {
    id: 'primitiveToObject',
    name: 'Primitive → Object/Array Mismatch',
    category: 'type_mismatch',
    description: 'Sends an object {} or array [] where a primitive value is expected',
    defaultEnabled: true,
    severity: 'high',
  },
  {
    id: 'integerToFloat',
    name: 'Integer → Floating Point (Decimal)',
    category: 'type_mismatch',
    description: 'Sends 42.75 for strictly typed integer fields',
    defaultEnabled: true,
    severity: 'medium',
  },

  // Unicode & Fuzzing
  {
    id: 'emojiSequences',
    name: 'High-Order UTF-8 Emojis (👨‍👩‍👧‍👦, 🔥, 🚀)',
    category: 'unicode_fuzz',
    description: 'Tests 4-byte UTF-8 encoding and Zero-Width Joiner (ZWJ) sequence support',
    defaultEnabled: true,
    severity: 'medium',
  },
  {
    id: 'rightToLeftOverride',
    name: 'Right-To-Left (RTL) & BiDi Overrides',
    category: 'unicode_fuzz',
    description: 'Injects Unicode \\u202E / RTL control characters to test rendering & sanitize filters',
    defaultEnabled: true,
    severity: 'medium',
  },
  {
    id: 'zeroWidthSpaces',
    name: 'Zero-Width Spaces & Invisible Characters',
    category: 'unicode_fuzz',
    description: 'Injects \\u200B and \\uFEFF characters to detect silent truncation or bypasses',
    defaultEnabled: true,
    severity: 'medium',
  },
  {
    id: 'sqlInjectionPatterns',
    name: 'SQL Injection Fuzz Vectors',
    category: 'unicode_fuzz',
    description: "Injects ' OR '1'='1 -- and SLEEP(5) patterns to ensure 400 Bad Request instead of 500",
    defaultEnabled: true,
    severity: 'high',
  },
  {
    id: 'xssScriptTags',
    name: 'Cross-Site Scripting (XSS) Vectors',
    category: 'unicode_fuzz',
    description: 'Injects <script>alert(1)</script> and <img src=x onerror=...>',
    defaultEnabled: true,
    severity: 'high',
  },
  {
    id: 'pathTraversalVectors',
    name: 'Directory / Path Traversal Vectors',
    category: 'unicode_fuzz',
    description: 'Injects ../../../../etc/passwd and ..\\\\..\\\\Windows\\\\win.ini',
    defaultEnabled: true,
    severity: 'high',
  },
  {
    id: 'extremeWhitespaceCrlf',
    name: 'CRLF & Whitespace Injection (\\r\\n)',
    category: 'unicode_fuzz',
    description: 'Injects Carriage Return / Line Feed characters to test HTTP header/body split bugs',
    defaultEnabled: true,
    severity: 'medium',
  },
];

export const DEFAULT_RULE_SELECTION: RuleSelectionState = {
  numericMinMinusOne: true,
  numericMaxPlusOne: true,
  numericZeroAndNegative: true,
  numericOverflow: true,
  stringMinLengthMinusOne: true,
  stringMaxLengthPlusOne: true,
  stringBufferOverflow: false,
  stringEmpty: true,
  arrayEmpty: true,
  arrayMaxItemsPlusOne: true,

  omitRequiredFields: true,
  explicitNullForNonNull: true,
  emptyObjectsForRequired: true,
  arrayNullItemInjection: false,

  stringToInteger: true,
  integerToString: true,
  booleanToString: true,
  primitiveToObject: true,
  integerToFloat: true,

  emojiSequences: true,
  rightToLeftOverride: true,
  zeroWidthSpaces: true,
  sqlInjectionPatterns: true,
  xssScriptTags: true,
  pathTraversalVectors: true,
  extremeWhitespaceCrlf: true,
};
