import JSZip from 'jszip';
import { GeneratedSuite } from '../types';

export async function generateTestBundleZip(suite: GeneratedSuite): Promise<Blob> {
  const zip = new JSZip();
  const { endpoint, postmanCollectionJson, playwrightSpecCode, timestamp } = suite;
  const safeName = (endpoint.name || 'api').toLowerCase().replace(/[^a-z0-9]+/g, '-');

  // 1. Playwright Test Suite
  zip.file(`tests/${safeName}.spec.ts`, playwrightSpecCode);

  // 2. Playwright Configuration file (playwright.config.ts)
  const playwrightConfig = `import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  testDir: './tests',
  timeout: 30000,
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : undefined,
  reporter: [['html'], ['list']],
  use: {
    baseURL: process.env.API_BASE_URL || ${JSON.stringify(endpoint.url)},
    extraHTTPHeaders: ${JSON.stringify(endpoint.headers || {}, null, 2)},
    trace: 'on-first-retry',
  },
});
`;
  zip.file('playwright.config.ts', playwrightConfig);

  // 3. Postman Collection v2.1
  zip.file(`postman/${safeName}-collection.json`, postmanCollectionJson);

  // 4. package.json for instant Playwright and Newman execution
  const packageJson = {
    name: `${safeName}-automated-tests`,
    version: '1.0.0',
    description: `Automated API Test Suite synthesized by SentinelPayload on ${timestamp}`,
    scripts: {
      "test:playwright": "playwright test",
      "test:playwright:ui": "playwright test --ui",
      "test:playwright:report": "playwright show-report",
      "test:newman": `newman run postman/${safeName}-collection.json --reporters cli,html`
    },
    devDependencies: {
      "@playwright/test": "^1.49.0",
      "newman": "^6.2.1"
    }
  };
  zip.file('package.json', JSON.stringify(packageJson, null, 2));

  // 5. README instructions
  const readmeContent = `# ${endpoint.name || 'API'} Automated Test Suite
Generated by **SentinelPayload (Client-Side API Mutation & Automated Test Generator)**
Timestamp: ${timestamp}

## Running Playwright API Tests (.spec.ts)
\`\`\`bash
# 1. Install dependencies
npm install

# 2. Run Playwright API test suite
npx playwright test

# 3. View Interactive Test Report
npx playwright show-report
\`\`\`

## Running Postman Collection (Newman CLI)
\`\`\`bash
# Run with Newman
npx newman run postman/${safeName}-collection.json
\`\`\`
`;
  zip.file('README.md', readmeContent);

  // Generate zip as Blob
  return await zip.generateAsync({ type: 'blob' });
}
