import { GeneratedSuite, MutationResult } from '../types';

export function compilePlaywrightSuite(suite: GeneratedSuite): string {
  const { endpoint, baselineVector, vectors, timestamp } = suite;
  const method = endpoint.method.toLowerCase();

  // Helper to format payload indentation
  function indentJson(obj: unknown, spaces: number = 6): string {
    const json = JSON.stringify(obj, null, 2);
    const indent = ' '.repeat(spaces);
    return json
      .split('\n')
      .map((line, idx) => (idx === 0 ? line : `${indent}${line}`))
      .join('\n');
  }

  // Category groupings
  const categoryBlocks: Record<string, { title: string; desc: string; vectors: MutationResult[] }> = {
    boundary: {
      title: '01 - Boundary Limit Violations',
      desc: 'Edge cases testing numeric limits, string length bounds, and array caps',
      vectors: [],
    },
    nullability: {
      title: '02 - Null & Missing Field Tests',
      desc: 'Edge cases verifying non-null constraints and required field omissions',
      vectors: [],
    },
    type_mismatch: {
      title: '03 - Type Mismatch Tests',
      desc: 'Edge cases ensuring strict typing rejection (strings as numbers, boolean traps)',
      vectors: [],
    },
    unicode_fuzz: {
      title: '04 - Unicode & Security Fuzzing',
      desc: 'Resilience vectors testing multi-byte UTF-8, RTL overrides, SQLi, and XSS sanitization',
      vectors: [],
    },
  };

  for (const v of vectors) {
    if (categoryBlocks[v.category]) {
      categoryBlocks[v.category].vectors.push(v);
    }
  }

  const codeLines: string[] = [
    `/**`,
    ` * Auto-generated by QA Schema Mutator & Dual-Target Test Synthesizer`,
    ` * Endpoint: ${endpoint.method} ${endpoint.url}`,
    ` * Generated At: ${timestamp}`,
    ` * Total Test Vectors: ${vectors.length + 1}`,
    ` *`,
    ` * RUNNING THIS SUITE:`,
    ` *   npx playwright test api-mutations.spec.ts`,
    ` */`,
    ``,
    `import { test, expect } from '@playwright/test';`,
    ``,
    `// Global Test Configuration`,
    `const BASE_URL = process.env.API_BASE_URL || ${JSON.stringify(endpoint.url)};`,
    `const HEADERS = ${indentJson(endpoint.headers || {}, 0)};`,
    ``,
    `test.describe('${endpoint.name || 'API'} Automated Verification Suite', () => {`,
    ``,
    `  // 00 - Happy Path Baseline`,
    `  test.describe('00 - Baseline (Happy Path)', () => {`,
    `    test('${baselineVector.name}', async ({ request }) => {`,
    `      const startTime = Date.now();`,
    `      const response = await request.${method}(BASE_URL, {`,
    `        data: ${indentJson(baselineVector.payload, 8)},`,
    `        headers: HEADERS,`,
    `      });`,
    ``,
    `      // Assert happy path status`,
    `      expect([200, 201]).toContain(response.status());`,
    ``,
    `      // Performance: SLA < 2000ms`,
    `      const latency = Date.now() - startTime;`,
    `      expect(latency).toBeLessThan(2000);`,
    ``,
    `      // Response validity`,
    `      const body = await response.json().catch(() => null);`,
    `      expect(body).not.toBeNull();`,
    `    });`,
    `  });`,
    ``,
  ];

  // Render each category block
  for (const [, group] of Object.entries(categoryBlocks)) {
    if (group.vectors.length === 0) continue;

    codeLines.push(`  // ${group.title}`);
    codeLines.push(`  test.describe('${group.title}', () => {`);

    for (const v of group.vectors) {
      // Escape single quotes in test name
      const safeTestName = v.name.replace(/'/g, "\\'");
      codeLines.push(`    test('${safeTestName}', async ({ request }) => {`);
      codeLines.push(`      // Rule ID: ${v.ruleId} | Target Pointer: ${v.fieldPointer}`);
      codeLines.push(`      // Description: ${v.description}`);
      codeLines.push(`      const startTime = Date.now();`);
      codeLines.push(`      const response = await request.${method}(BASE_URL, {`);
      codeLines.push(`        data: ${indentJson(v.mutatedPayload, 8)},`);
      codeLines.push(`        headers: HEADERS,`);
      codeLines.push(`      });`);
      codeLines.push(``);
      codeLines.push(`      // Assert rejection status: expects 400 Bad Request or 422 Unprocessable`);
      codeLines.push(`      expect([400, 422]).toContain(response.status());`);
      codeLines.push(``);
      codeLines.push(`      // Ensure server did not crash with 500 Internal Error`);
      codeLines.push(`      expect(response.status()).not.toBe(500);`);
      codeLines.push(``);
      codeLines.push(`      // Verify structured error diagnostic returned`);
      codeLines.push(`      const errorBody = await response.json().catch(() => null);`);
      codeLines.push(`      expect(errorBody).not.toBeNull();`);
      codeLines.push(``);
      codeLines.push(`      // Performance SLA check`);
      codeLines.push(`      expect(Date.now() - startTime).toBeLessThan(2000);`);
      codeLines.push(`    });`);
      codeLines.push(``);
    }

    codeLines.push(`  });`);
    codeLines.push(``);
  }

  codeLines.push(`});`);
  codeLines.push(``);

  return codeLines.join('\n');
}
