import { GeneratedSuite, MutationResult } from '../types';

interface PostmanItem {
  name: string;
  request: {
    method: string;
    header: Array<{ key: string; value: string; type: string }>;
    body?: {
      mode: string;
      raw: string;
      options: {
        raw: {
          language: string;
        };
      };
    };
    url: {
      raw: string;
      protocol?: string;
      host?: string[];
      path?: string[];
    };
    description?: string;
  };
  event: Array<{
    listen: string;
    script: {
      type: string;
      exec: string[];
    };
  }>;
}

interface PostmanFolder {
  name: string;
  item: PostmanItem[];
  description?: string;
}

export function compilePostmanCollection(suite: GeneratedSuite): string {
  const { endpoint, baselineVector, vectors, timestamp } = suite;

  // Helper to parse URL parts
  function parseUrl(rawUrl: string) {
    try {
      const parsed = new URL(rawUrl);
      return {
        raw: rawUrl,
        protocol: parsed.protocol.replace(':', ''),
        host: parsed.hostname.split('.'),
        path: parsed.pathname.split('/').filter(Boolean),
      };
    } catch {
      return {
        raw: rawUrl,
        host: ['{{baseUrl}}'],
        path: [],
      };
    }
  }

  // Format headers
  const headers = Object.entries(endpoint.headers || {}).map(([key, value]) => ({
    key,
    value,
    type: 'text',
  }));

  // Helper to build test script for baseline
  function buildBaselineScript(): string[] {
    return [
      `// Auto-generated by QA Schema Mutator on ${timestamp}`,
      `pm.test("Status code is 200 or 201 (Happy Path)", function () {`,
      `    pm.expect(pm.response.code).to.be.oneOf([200, 201]);`,
      `});`,
      ``,
      `pm.test("Response time is acceptable (< 2000ms)", function () {`,
      `    pm.expect(pm.response.responseTime).to.be.below(2000);`,
      `});`,
      ``,
      `pm.test("Response is valid JSON format", function () {`,
      `    pm.response.to.be.json;`,
      `});`,
    ];
  }

  // Helper to build test script for edge-case mutation
  function buildMutationScript(vector: MutationResult): string[] {
    return [
      `// Edge-case assertion for ${vector.name}`,
      `// Rule: ${vector.ruleId} | Field: ${vector.fieldPointer}`,
      `pm.test("Status code is 400 or 422 for edge-case rejection", function () {`,
      `    pm.expect(pm.response.code).to.be.oneOf([400, 422]);`,
      `});`,
      ``,
      `pm.test("Response time is under 2000ms", function () {`,
      `    pm.expect(pm.response.responseTime).to.be.below(2000);`,
      `});`,
      ``,
      `pm.test("Server does not crash with 500 Internal Error", function () {`,
      `    pm.expect(pm.response.code).to.not.equal(500);`,
      `});`,
      ``,
      `pm.test("Error response contains diagnostic error details", function () {`,
      `    var json = pm.response.json();`,
      `    pm.expect(json).to.be.an('object');`,
      `});`,
    ];
  }

  // Build baseline item
  const baselineItem: PostmanItem = {
    name: baselineVector.name,
    request: {
      method: endpoint.method,
      header: headers,
      body: {
        mode: 'raw',
        raw: JSON.stringify(baselineVector.payload, null, 2),
        options: { raw: { language: 'json' } },
      },
      url: parseUrl(endpoint.url),
      description: 'Baseline happy-path request with valid payload conforming to schema.',
    },
    event: [
      {
        listen: 'test',
        script: {
          type: 'text/javascript',
          exec: buildBaselineScript(),
        },
      },
    ],
  };

  // Group mutations by category
  const categoryFolders: Record<string, { title: string; desc: string; items: PostmanItem[] }> = {
    boundary: {
      title: '01 - Boundary Limit Violations',
      desc: 'Edge cases testing numeric min/max limits, string lengths, and array bounds.',
      items: [],
    },
    nullability: {
      title: '02 - Null & Missing Field Tests',
      desc: 'Edge cases verifying required field enforcement and non-null constraints.',
      items: [],
    },
    type_mismatch: {
      title: '03 - Type Mismatch Tests',
      desc: 'Edge cases validating type safety (string vs number, boolean coercion, objects).',
      items: [],
    },
    unicode_fuzz: {
      title: '04 - Unicode & Security Fuzzing',
      desc: 'Security edge cases with emojis, RTL overrides, zero-width chars, SQLi, and XSS.',
      items: [],
    },
  };

  for (const vector of vectors) {
    const targetFolder = categoryFolders[vector.category];
    if (!targetFolder) continue;

    const item: PostmanItem = {
      name: vector.name,
      request: {
        method: endpoint.method,
        header: headers,
        body: {
          mode: 'raw',
          raw: JSON.stringify(vector.mutatedPayload, null, 2),
          options: { raw: { language: 'json' } },
        },
        url: parseUrl(endpoint.url),
        description: vector.description,
      },
      event: [
        {
          listen: 'test',
          script: {
            type: 'text/javascript',
            exec: buildMutationScript(vector),
          },
        },
      ],
    };

    targetFolder.items.push(item);
  }

  // Construct top-level folder array
  const folders: PostmanFolder[] = [
    {
      name: '00 - Baseline (Happy Path)',
      description: 'Contains valid baseline test vectors verifying happy path responses.',
      item: [baselineItem],
    },
    ...Object.values(categoryFolders)
      .filter((cat) => cat.items.length > 0)
      .map((cat) => ({
        name: cat.title,
        description: cat.desc,
        item: cat.items,
      })),
  ];

  const collection = {
    info: {
      name: `${endpoint.name || 'API'} - Automated Verification Suite`,
      _postman_id: `qa-schema-mutator-${Date.now()}`,
      description: `Auto-generated edge-case verification test suite created by QA Schema Mutator on ${timestamp}.\nIncludes ${vectors.length} mutated test vectors testing boundaries, nullability, type mismatches, and fuzzing resilience.`,
      schema: 'https://schema.getpostman.com/json/collection/v2.1.0/collection.json',
    },
    item: folders,
    variable: [
      {
        key: 'baseUrl',
        value: endpoint.url,
        type: 'string',
      },
    ],
  };

  return JSON.stringify(collection, null, 2);
}
